# Home
home:
    path: /
    defaults:
        _controller: Application:Home:index
    methods: [GET]
    
# Sample
samples_list:
    path: /samples/
    defaults:
        _controller: Application:Samples:list
    methods: [GET]
samples_get:
    path: /samples/{title}/{id}/
    defaults:
        _controller: Application:Samples:get
    requirements:
        title: ([\w-]+)
        id: (\d+)
    methods: [GET]